// Turns whatever sits in frontend/assets/voice/<character>/ into a require map. Either format
// is fine — what matters is <key>.<number>.<ext>, where the number picks the line from lines.json.
// Metro cannot require a path it computes at runtime, so the map has to be written out.
//   node backend/server/tools/voice-index.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(here, '../../..');
const VOICE = path.join(ROOT, 'frontend/assets/voice');
const OUT = path.join(ROOT, 'frontend/assets/voice-index.js');
const CHARACTERS = ['bunny', 'dino'];

const body = CHARACTERS.map((who) => {
  const dir = path.join(VOICE, who);
  if (!fs.existsSync(dir)) return `  ${who}: {},`;
  const byKey = {};
  for (const file of fs.readdirSync(dir).sort()) {
    const m = file.match(/^(.+)\.(\d+)\.(?:m4a|mp3|wav)$/);
    if (!m) continue;
    (byKey[m[1]] ||= []).push(`require('./voice/${who}/${file}')`);
  }
  const keys = Object.entries(byKey)
    .map(([key, mods]) => `    '${key}': [${mods.join(', ')}],`)
    .join('\n');
  return keys ? `  ${who}: {\n${keys}\n  },` : `  ${who}: {},`;
}).join('\n');

fs.writeFileSync(
  OUT,
  `// Generated by backend/server/tools/voice-index.mjs — do not edit by hand.\n` +
    `export default {\n${body}\n};\n`
);
console.log(`wrote ${path.relative(ROOT, OUT)}`);
